// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'bookmark'
  | 'bookmark-add'
  | 'bookmark-delete'
  | 'label-disableZoteroOutline'
  | 'label-enableBookmark'
  | 'label-newNodeAsChild'
  | 'outline'
  | 'outline-add'
  | 'outline-collapse-all'
  | 'outline-delete'
  | 'outline-delete-confirm'
  | 'outline-edit-placeholder'
  | 'outline-empty-prompt'
  | 'outline-expand-all'
  | 'outline-save-to-pdf'
  | 'plugin-name'
  | 'pref-group-about'
  | 'pref-group-bookmark'
  | 'pref-help';
