// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableBookmark": boolean;
      "newNodeAsChild": boolean;
      "disableZoteroOutline": boolean;
    };
  }
}
